POST http://localhost:9090/events
content-type: application/json

{
  "name": "Test event",
  "description": "A test event",
  "location": "A test location",
  "dateTime": "2025-05-06T15:30:00.000Z"
}