DELETE http://localhost:9090/events/17
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Q1QGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ2Njc1MzQ5LCJ1c2VySWQiOjR9.K7BDcNoUh1X_QCk10Id1Tf7zfUNWAAcTfiimSaRhXvk