POST http://localhost:9090/events/16/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ2NjgzMTgwLCJ1c2VySWQiOjN9.6emA4ycR4Tv6Vj5hpIbomwiCdtivcRgv4hkubEvt1-o