POST http://localhost:9090/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ2Njk4OTcyLCJ1c2VySWQiOjN9.p0yRsMkhX4xRW8q00eGjWqO-vB7iuXa03Q26UUCEkOo

{
  "name": "Test event KZA_New",
  "description": "test event KZA_New",
  "location": "test location KZA_New",
  "dateTime": "2025-05-06T15:30:00.000Z"
}