POST http://localhost:9090/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ2NzAyMDM4LCJ1c2VySWQiOjJ9.EvHgshwYlXe3_673MLddjy91WXwkhJTkwWEXEJbpRUQ

{
  "name": "Test event UserId_2s",
  "description": "test event UserId_2s",
  "location": "test location UserId_2s",
  "dateTime": "2025-05-06T15:30:00.000Z"
}