DELETE http://localhost:9090/events/17
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ2NzAxODQ2LCJ1c2VySWQiOjN9.t90hIFH6Sdf8S1UxaWl4HWMQGs9LGEH6UGLK9rk5mLI